package calcModule;


/**
* calcModule/Calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Sunday, May 10, 2026 7:23:22 PM IST
*/

public interface Calculator extends CalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculator
