package calcModule;


/**
* calcModule/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Sunday, May 10, 2026 7:23:22 PM IST
*/

public interface CalculatorOperations 
{
  double add (double a, double b);
  double sub (double a, double b);
  double mul (double a, double b);
  double div (double a, double b);
} // interface CalculatorOperations
