package calcModule;

/**
* calcModule/CalculatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Sunday, May 10, 2026 7:23:22 PM IST
*/

public final class CalculatorHolder implements org.omg.CORBA.portable.Streamable
{
  public calcModule.Calculator value = null;

  public CalculatorHolder ()
  {
  }

  public CalculatorHolder (calcModule.Calculator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calcModule.CalculatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calcModule.CalculatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calcModule.CalculatorHelper.type ();
  }

}
